name: JohnWeiss
favicon: null
layout_spectrum: 0.25241
typography_spectrum: 0.5494223542045802
title: JohnWeiss
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#dedede'
    - '#5f5e5f'
    - '#939192'
  brandStrength: 0.08888699021190405
  lightness: 0.7016685514245182
  saturation: 0.9570617680437863
  rhythmicContrast: 0.0166998072527349
purpose: []
