name: JohnWeiss
favicon: null
layout_spectrum: 0.9573818952776492
typography_spectrum: 0.5494223542045802
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.08888699021190405
  lightness: 0.7016685514245182
  saturation: 0.9570617680437863
  rhythmicContrast: 0.0166998072527349
purpose: []
